import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="p-0 m-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4 w-full h-screen bg-gray-900">
        <span className="text-gray-100">おほー</span>
      </main>
    </div>
  );
};

// eslint-disable-next-line import/no-default-export
export default Home;
